apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ollama.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ollama.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ollama.fullname" . }}
    namespace: {{ .Release.Namespace }}
